[build]
  base = "SecureWealth-Project/frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  # This prevents minor warnings from failing the build
  CI = "false"
  # Ensures Node version compatibility
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
